#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bump1,          sensorTouch)
#pragma config(Sensor, dgtl3,  bump2,          sensorTouch)
#pragma config(Sensor, dgtl4,  bump3,          sensorTouch)
#pragma config(Sensor, dgtl11, red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port8,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int code[4] = {1, 1, 1, 1};
int user_input[4];
bool set_mode = false;
int n = 0;

void isCodeCorrect() {
	if (code[0] == user_input[0]) {
		if (code[1] == user_input[1]) {
			if (code[2] == user_input[2]) {
				if (code[3] == user_input[3]) {
					setServo(servoMotor, 127);
					n = 0;
				}
				else { n = 0; }
			}
			else { n = 0; }
		}
		else { n = 0; }
	}
	else { n = 0; }
}

bool isNewCode() {
	code = user_input;
	return true;
}

void set_new_code () {
	wait(0.25);
	code[0] = user_input[0];
	code[1] = user_input[1];
	code[2] = user_input[2];
	code[3] = user_input[3];
	set_mode = false;
	n = 0;
}

void code_generator(int n, int x) {
	wait(0.25);
	if (n < 4) {
		user_input[n] = x;
	}
}

task main() {


	while (1==1) {

		while (motor[servoMotor] == 0) {
			turnLEDOn(red);
			turnLEDOff(green);


			while (SensorValue[bump1] == 1) { code_generator(n, 1); if (n < 4) { n = n + 1; } break; }
			while (SensorValue[bump2] == 1) { code_generator(n, 2); if (n < 4) { n = n + 1; } break; }
			while (SensorValue[bump3] == 1) { code_generator(n, 3); if (n < 4) { n = n + 1; } break; }

			wait1Msec(10);

			if (n == 4) { isCodeCorrect(); break; }

		}

		while (motor[servoMotor] == 127) {
			turnLEDOff(red);

			if ((SensorValue[limitSwitch] == 1) & (set_mode == false)) {
				turnLEDOn(green);
				set_mode = true;
				wait(0.25);
			}

			if ((SensorValue[limitSwitch] == 1) & (set_mode == true)) {
				turnLEDOff(green);
				set_mode = false;
				wait(0.25);
			}

			while (set_mode == true) {

				while (SensorValue[bump1] == 1) { code_generator(n, 1); if (n < 4) { n = n + 1; } break; }
				while (SensorValue[bump2] == 1) { code_generator(n, 2); if (n < 4) { n = n + 1; } break; }
				while (SensorValue[bump3] == 1) { code_generator(n, 3); if (n < 4) { n = n + 1; } break; }

				wait1Msec(10);

				if (n == 4) {
					set_new_code();
					setServo(servoMotor, 0);
					break;
				}
			}
		}
	}
}
